#!/bin/bash

path="/opt/SP/users/ogwvfde1/Script"
host="http://deossevr.dc-ratingen.de:8001"
email2="ramana.bhamidipati@amdocs.com; Einav.Elmograby@amdocs.com;Ravi.Rathod@amdocs.com; SHARADAM@amdocs.com; Daksha.Borkar2@amdocs.com; ELVIRAL@Amdocs.com; vladislav.zbytovsky@amdocs.com; Saurav.Singh1@amdocs.com; ariel.lieberman@amdocs.com; Ronit.Rubins@Amdocs.com;AQEOffShoreOSFTesters@amdocs.com;"
email="suzan.labib@dxc.com; mohamed.al-sadek@dxc.com; infra-egypt-adm@dxc.com;"
env="INT.3"

a=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/ConvertAndValidateIBAN_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)
q=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/SubsidizedHandsetValidation_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)
c=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/GetCustomerDetails_KS_M2_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)
g=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/VFDEGetmarketingPermission_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)
w=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/GetAvailableShippingOptions_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)
e=$(grep -oP "<ErrorDescription>(.*)</ErrorDescription>" "$path"/VFDESetPermission_output.xml | cut -d ">" -f 2 | cut -d "<" -f 1)

da=`date +"%d-%m-%Y, %H.%M.%S"`
(
echo "From: AutoGenerated@noreply.com; "
echo "To: $email "
echo "Cc: $email2 "
echo "MIME-Version: 1.0"
echo "Content-Type: multipart/alternative; "
echo ' boundary="PAA08673.1018277622/server.xyz.com"'
echo "Subject: EAI Service Sanity Status Report: $env , $da  "
echo ""
echo "This is a MIME-encapsulated message"
echo ""
echo "--PAA08673.1018277622/server.xyz.com"
echo "Content-Type: text/html"
echo ""
echo "<html>
<head>
<style type="text/css">
	table {
		font-size: 12px;
		border: 1px solid #CCC; 
		font-family: Arial, Helvetica, sans-serif;
	} 
	td {
		padding: 4px;
		margin: 3px;
		border: 1px solid #CCC;
	}
	th {
		background-color: #104E8B; 
		color: #FFF;
		font-weight: bold;
	}
	.redtext {
        color: red;
	}

	.greentext {
        color: green;
	}
	p {
    		font-family: "Calibri";
		font-style: normal;
		font-size: 16px;
	}

</style>
</head>
<body>
<p>
Hi Team,<br>
<br>
Please see below table for status of EAI Services<br>
<br>
OSF Env: SIT.1 & SIT.4<br>
EAI Env: $env<br>
KIAS Env: ST349(MMC) & ST351(MMO)<br>
</p>"

echo "<body>
<table>
<tr><th>OGW Service Name</th><th>EAI Service Name</th><th>Output</th><th>Status</th></tr><tbody>"

if [ "$a" == "SUCCESS" ]
then
	echo "<tr><td>ConvertAndValidateIBAN</td><td>BankAccountUtility-001</td><td>${a}</td><td class="greentext">SUCCESS</td></tr>"	
	
else
	echo "<tr><td>ConvertAndValidateIBAN</td><td>BankAccountUtility-001</td><td>${a}</td><td class="redtext">FAILED</td></tr>"
fi

if [ "$q" == "SUCCESS" ]
then
	echo "<tr><td>SubsidizedHandsetValidation</td><td>MFSubProlongation-001</td><td>${q}</td><td class="greentext">SUCCESS</td></tr>"
	
	

else
	echo "<tr><td>SubsidizedHandsetValidation</td><td>MFSubProlongation-001</td><td>${q}</td><td class="redtext">FAILED</td></tr>"

fi
if [ "$c" == "SUCCESS" ]
then
	echo "<tr><td>GetCustomerDetails - KIAS</td><td>CustomerAccountService-002</td><td>${c}</td><td class="greentext">SUCCESS</td></tr>"
	
	

else
	echo "<tr><td>GetCustomerDetails - KIAS</td><td>CustomerAccountService-002</td><td>${c}</td><td class="redtext">FAILED</td></tr>"

fi
if [ "$g" == "SUCCESS" ]
then
	echo "<tr><td>GetMarketingPermission</td><td>CustomerInteraction-002</td><td>${g}</td><td class="greentext">SUCCESS</td></tr>"
	
	

else
	echo "<tr><td>GetMarketingPermission</td><td>CustomerInteraction-002</td><td>${g}</td><td class="redtext">FAILED</td></tr>"

fi
if [ "$e" == "SUCCESS" ]
then
	echo "<tr><td>SetMarketingPermission</td><td>CustomerInteractionService-003</td><td>${e}</td><td class="greentext">SUCCESS</td></tr>"
	
	

else
	echo "<tr><td>SetMarketingPermission</td><td>CustomerInteractionService-003</td><td>${e}</td><td class="redtext">FAILED</td></tr>"

fi
if [ "$w" == "SUCCESS" ]
then
	echo "<tr><td>GetAvailableShippingOptions</td><td>HardwareOrder-001</td><td>${w}</td><td class="greentext">SUCCESS</td></tr>"
	
	

else
	echo "<tr><td>GetAvailableShippingOptions</td><td>HardwareOrder-001</td><td>${w}</td><td class="redtext">FAILED</td></tr>"

fi

		
echo "</tbody></table>
<p>Automated Sanity Script</p>
</body>
</html>"
echo "--PAA08673.1018277622/server.xyz.com"
) | /usr/sbin/sendmail -t
